### ISSUE TITLE
How to find siganture moves for certain pokemon?

### ISSUE THREAD

**Issue by hneel** [PokeMiners/game_masters#2]
Hello,

I'm developping a tool which uses the game master file to make a list of available moves for certain pokemon. Now I can find all the regular and elite moves, but I have a problem with signature moves. 

For example: Giratina (both Altered and Origin) have signature move "Shadow Force". But when I search in the file for Shadow Force (in all combinations with or without spaces, hyphens, underscores, etc) I can't find anything that links this move to Giratina. 

What am I missing?

Thanks.

**Comment by thederekFawcett** [comment]
Shadow Force was a *historical move* on the Giratinas. Meaning they could learn it for that one week or whatever around Halloween, but it has not been enabled yet for them to learn it via Elite TM

**Comment by hneel** [comment]
Ah I see. I would have liked to be able to 'see' these kind of moves for the pokemon that have them. But if the info isnt't there, it's too bad. 
Thanks for your quick response.
