### ISSUE TITLE
no CaptureRate anymore?

### ISSUE THREAD

**Issue by svaningelgem** [PokeMiners/game_masters#4]
In the latest json file, there is no `captureRate` anymore? Only `obShadowFormBaseCaptureRate`. Is that intentionally? Or is it removed from the official version?

I also don't see immediately something that looks like a replacement for it. So I'm kind of hoping it's an issue in the generation ;-)

**Comment by marty0678** [comment]
Niantic has removed capture rate and flee rate from the GM so it's impossible to tell what those values are anymore.

**Comment by svaningelgem** [comment]
Pity! How do they determine it then?

**Comment by marty0678** [comment]
The server knows it, when you throw a ball it just asks the server if it was successful or not.
